"""increase_counter_name_length

Revision ID: 5d4b05f8f239
Revises: ddd6aa100b61
Create Date: 2026-04-23 19:42:50.382648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4b05f8f239'
down_revision: Union[str, Sequence[str], None] = 'ddd6aa100b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'counter_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('transaction', 'category',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('transaction', 'counter_name',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
