name: backend-python-pipeline
run-name:
on:
  push:
    paths:
      - "Backend_Python/**"
    branches:
      - "develop"
      - "main"
jobs:
  backend_python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend_Python
          file: Backend_Python/Dockerfile
          push: True
          tags: |
            yuriichechur/backend_python:${{github.run_number}} 
            yuriichechur/backend_python:latest

  deploy:
    runs-on: ubuntu-latest
    needs: backend_python

    steps:
      - uses: actions/checkout@v4

      - name: Debug SSH key lines
        run: echo "${{ secrets.SSH_KEY }}" | wc -l

      - name: Copy files to production via SSH
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ubuntu/FinancialManager/production
            curl -o /home/ubuntu/FinancialManager/production/docker-compose.yml \
              https://raw.githubusercontent.com/DusiEkler/FinancialManager/develop/docker-compose.yml
            cd /home/ubuntu/FinancialManager/production
            docker-compose pull backend_python
            docker-compose up backend_python --force-recreate -d

      - name: Copy files to staging via SSH
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            mkdir -p /home/ubuntu/FinancialManager/staging
            curl -o /home/ubuntu/FinancialManager/staging/docker-compose.yml \
              https://raw.githubusercontent.com/DusiEkler/FinancialManager/develop/docker-compose.yml
            cd /home/ubuntu/FinancialManager/staging
            docker-compose pull backend_python
            docker-compose up backend_python --force-recreate -d
