name: backend-python-pipeline
run-name:
on:
  push:
    paths:
      - "Backend_Python/**"
    branches:
      - "develop"
      - "main"
jobs:
  backend_python:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Lint python file
        run: |
          python3 -m venv venv
          venv/bin/pip install flake8
          venv/bin/flake8 Backend_Python/

      - name: Login in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./Backend_Python
          file: Backend_Python/Dockerfile
          push: True
          tags: |
            yuriichechur/backend_python:${{github.run_number}} 
            yuriichechur/backend_python:latest

  deploy:
    runs-on: self-hosted
    needs: backend_python

    steps:
      - uses: actions/checkout@v4

      - name: Login in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mkdir -p /home/ubuntu/FinancialManager/production
          cp docker-compose.yml /home/ubuntu/FinancialManager/production/
          cd /home/ubuntu/FinancialManager/production
          docker-compose pull backend_python
          docker-compose up backend_python --force-recreate -d

      - name: Deploy to Staging
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          mkdir -p /home/ubuntu/FinancialManager/staging
          cp docker-compose.yml /home/ubuntu/FinancialManager/staging/
          cd /home/ubuntu/FinancialManager/staging
          docker-compose pull backend_python
          docker-compose up backend_python --force-recreate -d
